### ISSUE TITLE
Upgrade to Ember 3

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/datadelivery-ui#42]
This project is currently using Ember 2.13.3 which is EOL.
We should upgrade to a 3+ LTS version of Ember: https://emberjs.com/releases/

**Comment by johnbradley** [comment]
The `ember-number-to-human-size` addon appears incompatible with ember 3:
https://github.com/kellysutton/ember-number-to-human-size/issues/5

**Comment by dleehr** [comment]
> The `ember-number-to-human-size` addon appears incompatible with ember 3:
> [kellysutton/ember-number-to-human-size#5](https://github.com/kellysutton/ember-number-to-human-size/issues/5)

Good catch. We can probably remove that addon and write our own helper. We do use it in bespin-ui as well. It formats bytes into GiB, so it's a pretty straightforward function.

**Comment by johnbradley** [comment]
Fixed in PR #45.
