### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/datadelivery-ui#58]
Building the docker image fails with: `Launcher Chrome not found. Not installed?`

Details from running `docker build .`:
```
Step 8/13 : RUN npm test
 ---> Running in 80e4d7e4777b

> datadelivery-ui@1.3.1 test /src
> ember test

- Building
Environment: test
- Building
- cleaning up
- cleaning up
cleaning up...
Built project successfully. Stored in "/src/tmp/class-tests_dist-xdHl6a9K.tmp".
not ok 1 [undefined ms] - Error
    ---
        message: >
            Launcher Chrome not found. Not installed?
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
Launcher Chrome not found. Not installed?


Stack Trace and Error Report: /tmp/error.dump.ee728d7757df3ff34c7c3aab27402a9f.log
npm ERR! Test failed.  See above for more details.
The command '/bin/sh -c npm test' returned a non-zero code: 1
```

**Comment by johnbradley** [comment]
Fails to build because testing now requires chrome instead of phantomjs.
Found some notes on installing headless chrome within docker:
https://developers.google.com/web/updates/2017/04/headless-chrome
This page references an [example Docker file](https://github.com/GoogleChromeLabs/lighthousebot/blob/master/builder/Dockerfile)

**Comment by dleehr** [comment]
The Circle config uses  `circleci/node:8.9-browsers` for that reason - it's got node and headless browsers installed. We could try that image as the base.

**Comment by johnbradley** [comment]
The`circleci/node:8.9-browsers` image sets USER to be `circleci`:
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/node/images/8.9.4/Dockerfile#L81

This causes permission issues when running `npm install`
```
npm WARN checkPermissions Missing write access to /src
npm ERR! path /src
npm ERR! code EACCES
```
Switch user back to root seems to fix this.
