### ISSUE TITLE
Allow new deliveries to be created

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/datadelivery-ui#6]
Requires a project browser, recipient chooser, etc.

**Comment by johnbradley** [comment]
To list projects we should be able to use the current D4S2 `/api/v2/duke-ds-projects/` endpoint.
To list recipients we could use the current D4S2 `/api/v2/duke-ds-users/`, but this only shows users who have logged into DukeDS. A better option would be to use `https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/getApiV1AuthProvidersIdAffiliates` to search for recipients as it is not limited for.

**Comment by dleehr** [comment]
Related: https://github.com/Duke-GCB/D4S2/issues/107
